services:
  web:
    container_name: TreeService.Web
    build: 
      context: .
      dockerfile: src/TreeService.API/Dockerfile
    ports:
      - "8080:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Docker
    depends_on:
      - postgres
      - seq
  postgres:
    container_name: TreeService.Postgres
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_DB: tree_database
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - "5464:5432"
  seq:
    container_name: TreeService.Seq
    image: datalust/seq:latest
    restart: always
    environment:
      - ACCEPT_EULA=Y
    ports:
      - "5341:5341"
      - "8081:80"
  nginx:
    container_name: TreeService.Nginx
    image: nginx:latest
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - web
volumes:
  postgres-data:
